### ISSUE TITLE
injectserver not working with react-native 0.44

### ISSUE THREAD

**Issue by chunghe** [jhen0409/remote-redux-devtools-on-debugger#22]
![2017-05-05 16 12 50](https://cloud.githubusercontent.com/assets/78242/25738097/ca5b0fa8-31ad-11e7-8fd1-cf889e1d4f31.png)

As the screenshot, after `injectserver`, the `<div id="remote-redux-devtools-on-debugger"></div>` will be inside `<audio>` tag. The redux debugger won't appear.

**Comment by jhen0409** [comment]
Thanks! Fixed with https://github.com/jhen0409/remote-redux-devtools-on-debugger/commit/433d140bd260f5c77431f874647ab1cbed3c0a36 first (released as [`v0.7.1`](https://github.com/jhen0409/remote-redux-devtools-on-debugger/releases/tag/v0.7.1)).

Maybe https://github.com/facebook/react-native/pull/13798 is the right way, but I'd not like to wait two months for release, unless it is cherry-pick for 0.44.
